# These are supported funding model platforms

github: sebastian-software # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ["https://sebastian-software.de", "mailto:s.werner@sebastian-software.de"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

