import { useLocation } from "react-router";

export function ApiPage() {
  const location = useLocation();
  const path = location.pathname.replace("/docs/api", "").replace(/^\//, "");

  // For now, show placeholder until TypeDoc generates content
  if (path === "" || path === "/") {
    return (
      <>
        <h1>API Reference</h1>
        <p>
          Complete API documentation generated from TypeScript source code using TypeDoc.
        </p>

        <h2>Core Functions</h2>
        <h3>transcribe(audioPath, options?)</h3>
        <p>Transcribe an audio or video file using the configured backend.</p>
        <pre>
          <code>{`import { transcribe } from "cuttledoc";

const result = await transcribe("audio.mp3", {
  language: "en",
  backend: "auto",
});`}</code>
        </pre>

        <h4>Parameters</h4>
        <ul>
          <li><code>audioPath</code> - Path to audio/video file</li>
          <li><code>options.language</code> - Language code (e.g., "en", "de")</li>
          <li><code>options.backend</code> - Backend to use: "auto", "apple", "whisper", "parakeet"</li>
        </ul>

        <h4>Returns</h4>
        <pre>
          <code>{`interface TranscriptionResult {
  text: string;
  segments: TranscriptionSegment[];
  durationSeconds: number;
  backend: string;
  language?: string;
  confidence?: number;
}`}</code>
        </pre>

        <h2>LLM Enhancement</h2>
        <h3>enhanceTranscript(text, options?)</h3>
        <p>Enhance a transcript using an LLM for formatting and corrections.</p>
        <pre>
          <code>{`import { enhanceTranscript } from "cuttledoc/llm";

const enhanced = await enhanceTranscript(transcriptText, {
  model: "gemma3n:e4b",
  mode: "enhance", // or "correct"
});`}</code>
        </pre>

        <h4>Parameters</h4>
        <ul>
          <li><code>text</code> - Raw transcript text</li>
          <li><code>options.model</code> - LLM model ID</li>
          <li><code>options.mode</code> - "enhance" (full formatting) or "correct" (minimal fixes)</li>
        </ul>

        <h4>Returns</h4>
        <pre>
          <code>{`interface LLMProcessResult {
  markdown: string;
  plainText: string;
  stats: {
    correctionsCount: number;
    paragraphCount: number;
    processingTimeMs: number;
  };
}`}</code>
        </pre>

        <h2>Configuration</h2>
        <h3>setBackend(backend)</h3>
        <p>Set the default backend for all transcriptions.</p>
        <pre>
          <code>{`import { setBackend } from "cuttledoc";

setBackend("apple"); // Use Apple Speech by default`}</code>
        </pre>

        <h3>getAvailableBackends()</h3>
        <p>Get list of available backends on the current platform.</p>
        <pre>
          <code>{`import { getAvailableBackends } from "cuttledoc";

const backends = getAvailableBackends();
// ["apple", "whisper", "parakeet"] on macOS`}</code>
        </pre>
      </>
    );
  }

  return (
    <>
      <h1>API: {path}</h1>
      <p>Documentation for this endpoint will be generated by TypeDoc.</p>
    </>
  );
}

